### ISSUE TITLE
Why not collaborate?

### ISSUE THREAD

**Issue by alexilyaev** [Donov4n/stylelint-find-new-rules#2]
Hi @Donov4n,

I created [stylelint-find-rules](https://github.com/alexilyaev/stylelint-find-rules)

It's really cool that you took it a step forward.  
I was wondering what was the reasoning behind making a new package instead of trying to collaborate on the exiting one (besides me not being so active on it)?

**Comment by Donov4n** [comment]
Hello @alexilyaev,

Thank you for your work on `stylelint-find-rules`.

I created this package due to the lake of activity / maintenance on the original one (olds deps, unresolved issues, ...).
  
Some time ago I needed quickly the ["recursive `extends`" support](https://github.com/alexilyaev/stylelint-find-rules/issues/9) but the ticket was not moving so i created this one.

Note that this project is a complete rewrite of the original one.  
The changes made in this project are too large to be merged back in the original project i think (?).  

Despite this, if you want to merge back these changes, no problem for me to delete this project.
